name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Build CI Docker image
        run: docker build --network=host -f Dockerfile.ci -t bangkah-ci .

      - name: Run tests in Docker Compose
        run: docker compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from ci

      - name: Copy coverage report from container
        run: |
          docker cp $(docker ps -a -q -f name=bangkah-ci-1):/app/coverage.xml ./coverage.xml || true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
